version: "3.8"

services:
  client:
    build:
      context: ./client
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080/query
    depends_on:
      - server

  server:
    build:
      context: ./server
      target: development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/go
    environment:
      - PORT=8080
      - CGO_ENABLED=0
      - GOOS=linux
      - BITCOIN_NODE_URL=http://host.docker.internal:18443
      - BITCOIN_NODE_USER=polaruser
      - BITCOIN_NODE_PASS=polarpass
