version: "3.8"

services:
  client:
    build:
      context: ./client
      target: production
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:8080/query

  server:
    build:
      context: ./server
      target: production
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
