// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BalanceResponse struct {
	Address string `json:"address"`
	Balance int32  `json:"balance"`
}

type Block struct {
	Hash              string  `json:"hash"`
	Confirmations     int32   `json:"confirmations"`
	Size              int32   `json:"size"`
	StrippedSize      int32   `json:"strippedSize"`
	Weight            int32   `json:"weight"`
	Height            int32   `json:"height"`
	Version           int32   `json:"version"`
	VersionHex        string  `json:"versionHex"`
	MerkeRoot         string  `json:"merkeRoot"`
	Time              int32   `json:"time"`
	MedianTime        int32   `json:"medianTime"`
	Nonce             int32   `json:"nonce"`
	Bits              string  `json:"bits"`
	Difficulty        float64 `json:"difficulty"`
	Chainwork         string  `json:"chainwork"`
	NTx               int32   `json:"nTx"`
	PreviousBlockHash string  `json:"previousBlockHash"`
	NextBlockHash     string  `json:"nextBlockHash"`
}

type LatestBlocksResponse struct {
	Height int32    `json:"height"`
	Blocks []*Block `json:"blocks"`
}

type Query struct {
}

type Transaction struct {
	Hex           string `json:"hex"`
	TxID          string `json:"txId"`
	Hash          string `json:"hash"`
	Size          int32  `json:"size"`
	Vsize         int32  `json:"vsize"`
	Weight        int32  `json:"weight"`
	Version       int32  `json:"version"`
	Locktime      int32  `json:"locktime"`
	BlockHash     string `json:"blockHash"`
	Confirmations int32  `json:"confirmations"`
	BlockTime     int32  `json:"blockTime"`
	Time          int32  `json:"time"`
}
