// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BalanceResponse struct {
	Address string `json:"address"`
	Balance int32  `json:"balance"`
}

type Query struct {
}
